version: "2.0"

dependencies:

  - project: kiegroup/droolsjbpm-build-bootstrap

  - project: kiegroup/kie-soup
    dependencies:
      - project: kiegroup/droolsjbpm-build-bootstrap

  - project: kiegroup/droolsjbpm-knowledge
    dependencies:
      - project: kiegroup/kie-soup

  - project: kiegroup/drools
    dependencies:
      - project: kiegroup/kie-soup

  - project: kiegroup/kogito-runtimes
    dependencies:
      - project: kiegroup/drools

  - project: kiegroup/kogito-apps
    dependencies:
      - project: kiegroup/kogito-runtimes

  - project: kiegroup/kogito-examples
    dependencies:
      - project: kiegroup/kogito-runtimes

default:
  build-command:
    current: mvn -e -nsu -Dfull -Pwildfly clean install -Prun-code-coverage  -Dcontainer.profile=wildfly -Dcontainer=wildfly -Dintegration-tests=true -Dmaven.test.failure.ignore=true -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3
    upstream: mvn -e -T1C clean install -DskipTests -Dgwt.compiler.skip=true -Dgwt.skipCompilation=true -Denforcer.skip=true -Dcheckstyle.skip=true -Dspotbugs.skip=true -Drevapi.skip=true -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3
    after:
      upstream: rm -rf ./*

build:
  - project: kiegroup/drools
    build-command:
      upstream: |
        mvn clean install -DskipTests -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3
        export DROOLS_VERSION=`mvn org.apache.maven.plugins:maven-help-plugin:evaluate -Dexpression=project.version | grep ^7`

  - project: kiegroup/kogito-runtimes
    build-command:
      upstream: |
        mvn clean install -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3
      current: |
        mvn clean install -Dversion.org.kie7={{ env.DROOLS_VERSION }} -Prun-code-coverage -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3 -Dversion.org.kie7=7.47.0-SNAPSHOT
        mvn validate -Psonarcloud-analysis -e -nsu -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3
        mvn -f kogito-runtimes-integration-tests/pom.xml clean install -Pintegration-tests -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3
    clone:
      - kogito-runtimes-integration-tests

  - project: kiegroup/kogito-apps
    build-command:
      upstream: |
        mvn clean install -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3
      current: |
        mvn clean install -Prun-code-coverage -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3
        mvn validate -Psonarcloud-analysis -e -nsu -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3

  - project: kiegroup/kogito-examples
    build-command:
      current: |
        mvn clean install -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3
        mvn -f kogito-examples-persistence/pom.xml clean install -Ppersistence -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3
        mvn -f kogito-examples-events/pom.xml clean install -Pevents -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3
    clone:
      - kogito-examples-persistence
      - kogito-examples-events
